@startuml
'https://plantuml.com/class-diagram

class Usuarios {
    --Metodos--
    + consultaCatalogo()
    + busquedaPorAutor()
}

class UsuariosRegistrados {
    --Atributos--
    - nombre : String
    - dni : String
    - correo : String
    - password : String
    --Metodos--
    + gestionUsuario()
    + hacerReserva()
    + renovaionPrestamo()
    + verHistorialPrestamo()
    + gestionListaFavorito()
    + comntarEnDocumentacion()
}

class NuevoUsuario {
    --Metodos--
    + AltaUsuario()
}

class AltosMandos {
    --Metodos--
    + AltaDocumentacion()
    + ModificacionDocumentacion()
    + AltaAutor()
    + ModificacionAutor()
    + AltaNoticias()
    + ModificacionNoticias()
    + EliminacionNoticias()
}

class Administrador {
    --Metodos--
    + ModificarTipoUsuario()
    + BajaUsuario()
    + BajaDocumento()
    + BajaAutor()
}

class Bibliotecario {

}

Bibliotecario -left-|> AltosMandos
AltosMandos <|-- Administrador
Usuarios <|-left- NuevoUsuario
Usuarios <|-- UsuariosRegistrados
UsuariosRegistrados <|-- AltosMandos

@enduml