@startuml
'https://plantuml.com/class-diagram

class Usuaris {
    --Metodes--
    + consultaCataleg()
    + cercaPerAutor()
}

class UsuarisRegistrats {
    --Atributs--
    - nom : String
    - dni : String
    - correu : String
    - contrasenya : String
    --Metodes--
    + gestioUsuari()
    + ferReserva()
    + renovacioPrestec()
    + veureHistorialPrestec()
    + gestioLlistaPreferits()
    + comentarEnDocumentacio()
}

class NouUsuari {
    --Metodes--
    + AltaUsuari()
}

class AltsMandos {
    --Metodes--
    + AltaDocumentacio()
    + ModificacioDocumentacio()
    + AltaAutor()
    + ModificacioAutor()
    + AltaNoticies()
    + ModificacioNoticies()
    + EliminacioNoticies()
}

class Bibliotecari {
}

class Administrador {
    --Metodes--
    + ModificarTipusUsuari()
    + BaixaUsuari()
    + BaixaDocument()
    + BaixaAutor()
}

NouUsuari -|> Usuaris
Usuaris <|-- UsuarisRegistrats
UsuarisRegistrats <|-- AltsMandos
AltsMandos <|-- Bibliotecari
AltsMandos <|-- Administrador
@enduml