@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Usuarios: as user
:Usuario NO registrado: as NO
:Usuario Registrado: as regist
:Bibliotecario: as biblio
:Administrador: as admin

NO --> user
regist --> user
biblio --> regist
admin --> biblio

rectangle Sistema_de_reservas_de_una_biblioteca {
    user --> (Consultar catálogo)
    user --> (Buscar por autor)

    NO --> (Registrarse)

    regist --> (Gestionar perfil)
    regist --> (Hacer reserva)
    regist --> (Renovar préstamo)
    regist --> (Ver historial)
    regist --> (Gestionar favoritos)
    regist --> (Comentar)

    biblio --> (Gestionar documentos)
    biblio --> (Gestionar autores)
    biblio --> (Publicar noticias)

    admin --> (Dar de baja usuarios)
    admin --> (Dar de baja documentos)
    admin --> (Modificar permisos)
}
@enduml