@startuml
'https://plantuml.com/class-diagram

class Usuaris {
    -- Metodes --
    + consultaCataleg()
    + cercaPerAutor()
}

class UsuarisNoRegistrats {
    -- Metodes --
    + demanarAlta()
}

class UsuarisRegistrats {
    -- Atributs --
    - nom : String
    - dni : String
    - correu : String
    - contrasenya : String
    -- Metodes --
    + gestioUsuari()
    + ferReserva()
    + renovarPrestec()
    + veureHistorial()
    + gestionarPreferits()
    + afegirComentari()
}

class Bibliotecari {
    -- Metodes --
    + altaDocument()
    + modificarDocument()
    + altaAutor()
    + modificarAutor()
    + publicarNoticia()
    + modificarNoticia()
    + eliminarNoticia()
}

class Administrador {
    -- Metodes --
    + modificarTipusUsuari()
    + baixaUsuari()
    + baixaDocument()
    + baixaAutor()
}

Usuaris <|-- UsuarisNoRegistrats
Usuaris <|-- UsuarisRegistrats
UsuarisRegistrats <|-- Bibliotecari
Bibliotecari <|-- Administrador

@enduml